// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace RazorPagesSample.Models;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }
}