// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RazorPagesSample.Models;

public partial class User
{
    public User()
    {
    }

    public User(int id, string name, string password)
    {
        Id = id;
        Name = name;
        Password = password;
    }

    public int Id { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }
}