// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using static ConfigurationLibrary.Classes.ConfigurationHelper;
using AdminApplication.Models;
using EntityCoreFileLogger;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AdminApplication.Data;

public partial class EFEncryptPropertyValuesContext : DbContext
{
    public EFEncryptPropertyValuesContext(DbContextOptions<EFEncryptPropertyValuesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Password).IsRequired();
        });

        modelBuilder.Entity<User>().Property(e => e.Password).HasConversion(
            v => BC.HashPassword(v),
            v => v);

        OnModelCreatingPartial(modelBuilder);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .LogTo(new DbContextToFileLogger().Log,
                [DbLoggerCategory.Database.Command.Name],
                LogLevel.Information)
            .UseSqlServer(ConnectionString())
            .EnableSensitiveDataLogging();
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}